version: '3'

services:
  #MySQL Service
  note_db:
    image: mysql:5.7.22
    tty: true
    volumes:
      - note_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'note'
      MYSQL_ROOT_PASSWORD: '123456'
      SERVICE_TAGS: dev
      SERVICE_NAME: note_db

  #web Service
  note_api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - note_db
#Volumes
volumes:
  note_data:
