version: '3'

services:

  #api Service
  api:
    image: api:latest
    deploy:
      restart_policy:
        condition: any
    ports:
      - 8000:8000

  web:
    deploy:
      restart_policy:
        condition: any
    image: web:latest
    ports:
      - 80:80
