version: '3'
 
services:
  web:
    build: 
      dockerfile: dev.Dockerfile
      context: .
    ports:
      - 8081:8080
    image: lifestores/pharmiq-web:dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: yarn start